// Command apidoc regenerates the reference files in starlings/docs from Discord's
// official OpenAPI description, and measures how much of that surface starlings
// actually implements.
//
// Coverage is derived from the source rather than maintained by hand: every
// REST call in starlings carries a Route field naming its rate-limit bucket, and
// this tool parses those out of the AST and matches them against the spec. A
// route that is not implemented cannot be accidentally reported as covered.
//
// Usage, from the starlings directory:
//
//	go run ./internal/apidoc            # download the spec, regenerate docs
//	go run ./internal/apidoc -spec f.json
package main

import (
	"encoding/json/jsontext"
	json "encoding/json/v2"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"
)

const (
	specCommit = "a8693cc7e4230ebc6a9d68c31d5eb7ee81ab1069"
	specURL    = "https://raw.githubusercontent.com/discord/discord-api-spec/" + specCommit + "/specs/openapi.json"
)

var sourceRevision = specCommit

func generatedNotice() string {
	return "Generated by `internal/apidoc` from Discord's OpenAPI spec at `" + sourceRevision + "`; do not edit by hand.\n" +
		"The source spec is MIT-licensed; see [`THIRD_PARTY_NOTICES.md`](../THIRD_PARTY_NOTICES.md).\n\n"
}

func main() {
	specPath := flag.String("spec", "", "path to a local openapi.json (downloads it if empty)")
	specRevision := flag.String("spec-revision", "", "revision label for a local spec file")
	srcDir := flag.String("src", ".", "starlings package directory to measure coverage against")
	outDir := flag.String("out", "docs", "directory to write the markdown into")
	flag.Parse()
	if *specPath != "" {
		sourceRevision = "local file (revision not declared)"
		if *specRevision != "" {
			sourceRevision = *specRevision
		}
	}

	raw, err := loadSpec(*specPath)
	if err != nil {
		fatal(err)
	}

	var d doc
	if err := json.Unmarshal(raw, &d); err != nil {
		fatal(fmt.Errorf("parsing spec: %w", err))
	}
	if err := os.MkdirAll(*outDir, 0o755); err != nil {
		fatal(err)
	}

	implemented, err := implementedRoutes(*srcDir)
	if err != nil {
		fatal(fmt.Errorf("reading starlings sources: %w", err))
	}

	nOps, nRes := writeREST(d, *outDir)
	nObjects, nEnums := writeSchemas(d, *outDir)
	covered, total := writeCoverage(d, implemented, *outDir)

	fmt.Printf("rest-surface.md  %d operations, %d resource groups\n", nOps, nRes)
	fmt.Printf("schemas.md       %d object schemas\n", nObjects)
	fmt.Printf("enums.md         %d enumerations\n", nEnums)
	fmt.Printf("coverage.md      %d/%d operations have declared routes (%.1f%%)\n",
		covered, total, 100*float64(covered)/float64(total))
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "apidoc:", err)
	os.Exit(1)
}

func loadSpec(path string) ([]byte, error) {
	if path != "" {
		return os.ReadFile(path)
	}
	c := &http.Client{Timeout: 3 * time.Minute}
	resp, err := c.Get(specURL)
	if err != nil {
		return nil, fmt.Errorf("downloading spec: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("downloading spec: %s", resp.Status)
	}
	return io.ReadAll(resp.Body)
}

// The spec

type doc struct {
	Paths      map[string]map[string]jsontext.Value `json:"paths"`
	Components struct {
		Schemas map[string]jsontext.Value `json:"schemas"`
	} `json:"components"`
}

type operation struct {
	OperationID string `json:"operationId"`
	Description string `json:"description"`
	Deprecated  bool   `json:"deprecated"`
}

type schema struct {
	Description string                    `json:"description"`
	Enum        []jsontext.Value          `json:"enum"`
	OneOf       []jsontext.Value          `json:"oneOf"`
	Properties  map[string]jsontext.Value `json:"properties"`
	Required    []string                  `json:"required"`
}

var httpMethods = map[string]bool{
	"get": true, "post": true, "put": true, "patch": true, "delete": true,
}

type specOp struct {
	Method, Path, ID string
	Deprecated       bool
}

// eachOp calls fn for every HTTP operation in the spec.
func (d doc) eachOp(fn func(specOp)) {
	for path, item := range d.Paths {
		for method, raw := range item {
			if !httpMethods[strings.ToLower(method)] {
				continue
			}
			var o operation
			if err := json.Unmarshal(raw, &o); err != nil {
				continue
			}
			fn(specOp{strings.ToUpper(method), path, o.OperationID, o.Deprecated})
		}
	}
}

// resourceOf groups an operation by the deepest non-parameter segment, which
// is roughly how Discord's own docs organise the API.
func resourceOf(path string) string {
	segs := strings.Split(strings.Trim(path, "/"), "/")
	if len(segs) == 0 {
		return "root"
	}
	head := segs[0]
	for i := 1; i < len(segs); i++ {
		if !strings.HasPrefix(segs[i], "{") {
			return head + "/" + segs[i]
		}
	}
	return head
}

// Coverage from AST

var placeholder = regexp.MustCompile(`\{[^}]*\}`)

// normalizeRoute reduces a route to a shape that can be compared across the
// spec and Starlings' source: every path parameter, however it is spelled, becomes
// a bare {}.
func normalizeRoute(s string) string {
	s = placeholder.ReplaceAllString(s, "{}")
	s = strings.TrimSuffix(s, "/")
	return s
}

// implementedRoutes parses Starlings' sources and returns the set of normalized
// "METHOD /path" routes that appear in a request literal's Route field.
func implementedRoutes(dir string) (map[string]bool, error) {
	fset := token.NewFileSet()
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}

	routes := map[string]bool{}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") || strings.HasSuffix(entry.Name(), "_test.go") {
			continue
		}
		file, err := parser.ParseFile(fset, filepath.Join(dir, entry.Name()), nil, 0)
		if err != nil {
			return nil, err
		}
		ast.Inspect(file, func(n ast.Node) bool {
			lit, ok := n.(*ast.CompositeLit)
			if !ok {
				return true
			}
			id, ok := lit.Type.(*ast.Ident)
			if !ok || id.Name != "request" {
				return true
			}
			for _, elt := range lit.Elts {
				kv, ok := elt.(*ast.KeyValueExpr)
				if !ok {
					continue
				}
				key, ok := kv.Key.(*ast.Ident)
				if !ok || key.Name != "Route" {
					continue
				}
				if r := flattenString(kv.Value); r != "" {
					routes[normalizeRoute(r)] = true
				}
			}
			return true
		})
	}
	return routes, nil
}

// flattenString renders a string-concatenation expression, replacing every
// non-literal operand with {} - so `"GET /channels/" + id.String()` becomes
// "GET /channels/{}".
func flattenString(e ast.Expr) string {
	switch v := e.(type) {
	case *ast.BasicLit:
		if v.Kind != token.STRING {
			return "{}"
		}
		s, err := strconv.Unquote(v.Value)
		if err != nil {
			return "{}"
		}
		return s
	case *ast.BinaryExpr:
		if v.Op != token.ADD {
			return "{}"
		}
		return flattenString(v.X) + flattenString(v.Y)
	case *ast.ParenExpr:
		return flattenString(v.X)
	default:
		return "{}"
	}
}

func writeCoverage(d doc, implemented map[string]bool, outDir string) (covered, total int) {
	type row struct {
		op   specOp
		have bool
	}
	byRes := map[string][]row{}

	d.eachOp(func(o specOp) {
		total++
		key := normalizeRoute(o.Method + " " + o.Path)
		have := implemented[key]
		if have {
			covered++
		}
		res := resourceOf(o.Path)
		byRes[res] = append(byRes[res], row{o, have})
	})

	names := make([]string, 0, len(byRes))
	for r := range byRes {
		names = append(names, r)
	}
	sort.Strings(names)

	f, err := os.Create(filepath.Join(outDir, "coverage.md"))
	if err != nil {
		fatal(err)
	}
	defer f.Close()

	fmt.Fprint(f, "# starlings REST coverage\n\n")
	fmt.Fprint(f, "Measured, not asserted. Every REST call in starlings carries a `Route` naming its\n")
	fmt.Fprint(f, "rate-limit bucket; `internal/apidoc` parses those out of the AST and matches\n")
	fmt.Fprint(f, "them against Discord's official spec. Regenerate with `go run ./internal/apidoc`.\n\n")
	fmt.Fprint(f, generatedNotice())
	fmt.Fprint(f, "This measures declared source routes. It does not claim that every operation has been exercised against a live application.\n\n")
	fmt.Fprintf(f, "**%d of %d operations have declared routes (%.1f%%).**\n\n",
		covered, total, 100*float64(covered)/float64(total))

	// Routes starlings declares that the spec does not know about are almost always
	// a typo in a bucket key, which would silently break rate limiting.
	specKeys := map[string]bool{}
	d.eachOp(func(o specOp) { specKeys[normalizeRoute(o.Method+" "+o.Path)] = true })
	var orphans []string
	for r := range implemented {
		if !specKeys[r] {
			orphans = append(orphans, r)
		}
	}
	sort.Strings(orphans)
	if len(orphans) > 0 {
		fmt.Fprint(f, "## Routes starlings declares that the spec does not have\n\n")
		fmt.Fprint(f, "Each of these is either a typo in a bucket key or an endpoint outside the\n")
		fmt.Fprint(f, "documented surface. A typo here breaks rate limiting silently.\n\n")
		for _, o := range orphans {
			fmt.Fprintf(f, "- `%s`\n", o)
		}
		fmt.Fprintln(f)
	}

	fmt.Fprint(f, "## By resource\n\n| resource | implemented | total |\n| --- | --- | --- |\n")
	for _, r := range names {
		n := 0
		for _, rw := range byRes[r] {
			if rw.have {
				n++
			}
		}
		fmt.Fprintf(f, "| %s | %d | %d |\n", r, n, len(byRes[r]))
	}

	fmt.Fprint(f, "\n## Every operation\n")
	for _, r := range names {
		rows := byRes[r]
		sort.Slice(rows, func(i, j int) bool {
			if rows[i].op.Path != rows[j].op.Path {
				return rows[i].op.Path < rows[j].op.Path
			}
			return rows[i].op.Method < rows[j].op.Method
		})
		fmt.Fprintf(f, "\n### %s\n\n|  | method | path |\n| --- | --- | --- |\n", r)
		for _, rw := range rows {
			mark := " "
			if rw.have {
				mark = "x"
			}
			fmt.Fprintf(f, "| [%s] | `%s` | `%s` |\n", mark, rw.op.Method, rw.op.Path)
		}
	}
	return covered, total
}

// Doc writers

func writeREST(d doc, outDir string) (ops, resources int) {
	byRes := map[string][]specOp{}
	d.eachOp(func(o specOp) {
		ops++
		byRes[resourceOf(o.Path)] = append(byRes[resourceOf(o.Path)], o)
	})

	names := make([]string, 0, len(byRes))
	for r := range byRes {
		names = append(names, r)
	}
	sort.Strings(names)

	f, err := os.Create(filepath.Join(outDir, "rest-surface.md"))
	if err != nil {
		fatal(err)
	}
	defer f.Close()

	fmt.Fprint(f, "# Discord REST API surface\n\n")
	fmt.Fprint(f, "Every HTTP operation in Discord's official OpenAPI description of the v10 API.\n")
	fmt.Fprint(f, generatedNotice())
	fmt.Fprintf(f, "**%d operations across %d resource groups.**\n\n", ops, len(names))

	fmt.Fprint(f, "## Index\n\n| resource | operations |\n| --- | --- |\n")
	for _, r := range names {
		fmt.Fprintf(f, "| %s | %d |\n", r, len(byRes[r]))
	}

	fmt.Fprint(f, "\n## Operations\n")
	for _, r := range names {
		rows := byRes[r]
		sort.Slice(rows, func(i, j int) bool {
			if rows[i].Path != rows[j].Path {
				return rows[i].Path < rows[j].Path
			}
			return rows[i].Method < rows[j].Method
		})
		fmt.Fprintf(f, "\n### %s\n\n| method | path | operation |\n| --- | --- | --- |\n", r)
		for _, o := range rows {
			id := o.ID
			if o.Deprecated {
				id += " **(deprecated)**"
			}
			fmt.Fprintf(f, "| `%s` | `%s` | %s |\n", o.Method, o.Path, id)
		}
	}
	return ops, len(names)
}

// enumMember is one variant of a Discord enum. The spec encodes these as oneOf
// branches carrying a title and a const, not as a plain JSON Schema enum.
type enumMember struct{ Title, Description, Const string }

// enumMembers reports whether a schema is an enumeration and, if so, returns
// its variants in declaration order.
func enumMembers(s schema) ([]enumMember, bool) {
	if len(s.Enum) > 0 {
		out := make([]enumMember, 0, len(s.Enum))
		for _, v := range s.Enum {
			out = append(out, enumMember{Const: unquote(v)})
		}
		return out, true
	}
	if len(s.OneOf) == 0 {
		return nil, false
	}
	out := make([]enumMember, 0, len(s.OneOf))
	for _, raw := range s.OneOf {
		var m struct {
			Title       string         `json:"title"`
			Description string         `json:"description"`
			Const       jsontext.Value `json:"const"`
		}
		if err := json.Unmarshal(raw, &m); err != nil || len(m.Const) == 0 {
			// A branch with no const means this is a real union, not an enum.
			return nil, false
		}
		out = append(out, enumMember{m.Title, m.Description, unquote(m.Const)})
	}
	return out, true
}

func writeSchemas(d doc, outDir string) (objects, enums int) {
	names := make([]string, 0, len(d.Components.Schemas))
	for n := range d.Components.Schemas {
		names = append(names, n)
	}
	sort.Strings(names)

	var enumBody, objBody strings.Builder
	for _, n := range names {
		var s schema
		if err := json.Unmarshal(d.Components.Schemas[n], &s); err != nil {
			continue
		}

		if members, ok := enumMembers(s); ok {
			enums++
			fmt.Fprintf(&enumBody, "## %s\n\n", n)
			if s.Description != "" {
				fmt.Fprintf(&enumBody, "%s\n\n", oneLine(s.Description))
			}
			fmt.Fprint(&enumBody, "| value | name | meaning |\n| --- | --- | --- |\n")
			for _, m := range members {
				fmt.Fprintf(&enumBody, "| `%s` | `%s` | %s |\n", m.Const, m.Title, oneLine(m.Description))
			}
			fmt.Fprintln(&enumBody)
			continue
		}

		objects++
		fmt.Fprintf(&objBody, "## %s\n\n", n)
		if s.Description != "" {
			fmt.Fprintf(&objBody, "%s\n\n", oneLine(s.Description))
		}
		if len(s.Properties) == 0 {
			fmt.Fprint(&objBody, "_(no properties - a union or primitive alias)_\n\n")
			continue
		}

		req := map[string]bool{}
		for _, r := range s.Required {
			req[r] = true
		}
		props := make([]string, 0, len(s.Properties))
		for p := range s.Properties {
			props = append(props, p)
		}
		sort.Strings(props)

		fmt.Fprint(&objBody, "| field | required | type |\n| --- | --- | --- |\n")
		for _, p := range props {
			fmt.Fprintf(&objBody, "| `%s` | %s | %s |\n", p, yesNo(req[p]), typeOf(s.Properties[p]))
		}
		fmt.Fprintln(&objBody)
	}

	write(filepath.Join(outDir, "enums.md"),
		"# Discord API enumerations\n\n"+
			"Every enumerated type in the official spec, with its exact wire values. These\n"+
			"are the constants a library has to declare, and getting one wrong is a silent\n"+
			"bug, so they are transcribed rather than remembered.\n"+
			generatedNotice()+
			fmt.Sprintf("**%d enumerations.**\n\n", enums)+enumBody.String())

	write(filepath.Join(outDir, "schemas.md"),
		"# Discord API object model\n\n"+
			"Every object schema in the official spec. A `Request` suffix is a payload you\n"+
			"send; a `Response` suffix is what Discord returns.\n"+
			generatedNotice()+
			fmt.Sprintf("**%d object schemas.**\n\n", objects)+objBody.String())

	return objects, enums
}

func write(path, content string) {
	content = strings.TrimRight(content, "\n") + "\n"
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		fatal(err)
	}
}

func yesNo(b bool) string {
	if b {
		return "yes"
	}
	return ""
}

// typeOf renders a property's type compactly: a $ref name, a primitive, or an
// array/union summary.
func typeOf(raw jsontext.Value) string {
	var p struct {
		Ref   string           `json:"$ref"`
		Type  jsontext.Value   `json:"type"`
		Items jsontext.Value   `json:"items"`
		AnyOf []jsontext.Value `json:"anyOf"`
		OneOf []jsontext.Value `json:"oneOf"`
		AllOf []jsontext.Value `json:"allOf"`
	}
	if err := json.Unmarshal(raw, &p); err != nil {
		return "?"
	}
	switch {
	case p.Ref != "":
		return "`" + refName(p.Ref) + "`"
	case len(p.Items) > 0:
		return "array of " + typeOf(p.Items)
	case len(p.AnyOf) > 0:
		return union(p.AnyOf)
	case len(p.OneOf) > 0:
		return union(p.OneOf)
	case len(p.AllOf) > 0:
		return union(p.AllOf)
	case len(p.Type) > 0:
		return "`" + unquote(p.Type) + "`"
	}
	return "?"
}

// union renders a choice of types, collapsing the "or null" that the spec
// spells out on almost every optional field.
func union(parts []jsontext.Value) string {
	seen := map[string]bool{}
	out := make([]string, 0, len(parts))
	for _, v := range parts {
		t := typeOf(v)
		if t == "`null`" || seen[t] {
			continue
		}
		seen[t] = true
		out = append(out, t)
	}
	if len(out) == 0 {
		return "`null`"
	}
	return strings.Join(out, " or ")
}

func refName(ref string) string { return ref[strings.LastIndex(ref, "/")+1:] }

func unquote(v jsontext.Value) string {
	return strings.Trim(strings.TrimSpace(string(v)), `"`)
}

// oneLine flattens a description into a single table cell. Pipes are escaped so
// they do not split the cell, and em dashes are folded to hyphens: Discord's own
// field descriptions are full of them, and without this every regeneration would
// put them back into the docs.
func oneLine(s string) string {
	s = strings.ReplaceAll(s, "—", "-")
	return strings.ReplaceAll(strings.Join(strings.Fields(s), " "), "|", `\|`)
}
